# Site settings
title: ufutgs
twitter_username: ufutgs
name: Goo Jun Xi

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ufutgs


#Any buzzword skills you want to include
skills:
 - Java (intermediate level)
 - Python (intermediate level)
 - HTML (intermediate level)
 - javascript(beginner level)



#Education is required
education:
 - level: Bachelor of Engineering (still pursuing)
   date: 2020
   school: University of Technology and Design





#List of interesting Github repo/projects to include - optional
My Projects:
 - ufutgs/TibaiDBT
 - ufutgs/SUTD-1D-project
 - ufutgs/FoonyewArtWork
 - ufutgs/weaponClassesCombatSystem


intro: |
  I am an engineering student who highly interest in game development. I had worked on several projects while I was in high school, such as Unity and Unreal Engine 4. Now , I am focus on coding minecraft plugin using Java.<br/><br/>
  Besides that, I was learning web development such as Laravel, JavaScript, HTML, and SQL, during my late high school life. <br/><br/>
  I am a active person during the development process, loving to brainstorm game mechanism and code efficiency.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>:I learn it from my univerisity's course , So I do not have a lot of experience on writing python, but I have a text-based game project written in python as my university project..<br/><br/>
   <strong>Java</strong>:I have about 7months expirience in coding Java and I had written several minecraft plugins using spigot API. All of my project are inside "My Project" section. <br/><br/>
 
